// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings for `src/ggwave_flutter.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class GgwaveFlutterBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GgwaveFlutterBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GgwaveFlutterBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int sum(
    int a,
    int b,
  ) {
    return _sum(
      a,
      b,
    );
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.IntPtr, ffi.IntPtr)>>(
          'sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int sum_long_running(
    int a,
    int b,
  ) {
    return _sum_long_running(
      a,
      b,
    );
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.IntPtr, ffi.IntPtr)>>(
          'sum_long_running');
  late final _sum_long_running =
      _sum_long_runningPtr.asFunction<int Function(int, int)>();

  void initNative() {
    return _initNative();
  }

  late final _initNativePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('initNative');
  late final _initNative = _initNativePtr.asFunction<void Function()>();

  ffi.Pointer<ffi.Int8> sendMessage(
    ffi.Pointer<ffi.Int8> dataBuffer,
    int dataSize,
  ) {
    return _sendMessage(
      dataBuffer,
      dataSize,
    );
  }

  late final _sendMessagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Int8> Function(
              ffi.Pointer<ffi.Int8>, ffi.Int32)>>('sendMessage');
  late final _sendMessage = _sendMessagePtr
      .asFunction<ffi.Pointer<ffi.Int8> Function(ffi.Pointer<ffi.Int8>, int)>();

  int convertDataToAudio(
    ffi.Pointer<ffi.Int8> dataBuffer,
    int dataSize,
    ffi.Pointer<ffi.Int8> out,
  ) {
    return _convertDataToAudio(
      dataBuffer,
      dataSize,
      out,
    );
  }

  late final _convertDataToAudioPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Int8>, ffi.Int32,
              ffi.Pointer<ffi.Int8>)>>('convertDataToAudio');
  late final _convertDataToAudio = _convertDataToAudioPtr.asFunction<
      int Function(ffi.Pointer<ffi.Int8>, int, ffi.Pointer<ffi.Int8>)>();

  int convertDataToAudio2(
    ffi.Pointer<ffi.Int8> dataBuffer,
    int dataSize,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> out,
  ) {
    return _convertDataToAudio2(
      dataBuffer,
      dataSize,
      out,
    );
  }

  late final _convertDataToAudio2Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Int8>, ffi.Int32,
              ffi.Pointer<ffi.Pointer<ffi.Int8>>)>>('convertDataToAudio2');
  late final _convertDataToAudio2 = _convertDataToAudio2Ptr.asFunction<
      int Function(
          ffi.Pointer<ffi.Int8>, int, ffi.Pointer<ffi.Pointer<ffi.Int8>>)>();

  int getRequiredBufferSize(
    ffi.Pointer<ffi.Int8> dataBuffer,
    int dataSize,
  ) {
    return _getRequiredBufferSize(
      dataBuffer,
      dataSize,
    );
  }

  late final _getRequiredBufferSizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<ffi.Int8>, ffi.Int32)>>('getRequiredBufferSize');
  late final _getRequiredBufferSize = _getRequiredBufferSizePtr
      .asFunction<int Function(ffi.Pointer<ffi.Int8>, int)>();

  int test(
    ffi.Pointer<ffi.Int8> out,
  ) {
    return _test(
      out,
    );
  }

  late final _testPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Int8>)>>(
          'test');
  late final _test = _testPtr.asFunction<int Function(ffi.Pointer<ffi.Int8>)>();

  void bar(
    ffi.Pointer<ffi.Pointer<ffi.Int32>> x,
  ) {
    return _bar(
      x,
    );
  }

  late final _barPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Int32>>)>>('bar');
  late final _bar =
      _barPtr.asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Int32>>)>();
}
